# Generated by Django 4.1.7 on 2023-02-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('detial_see', 'Can read Detial all books')]},
        ),
    ]
