# Generated by Django 4.1.7 on 2023-02-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('detial_see', 'Can read Detial all books')]},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
